"""initial

Revision ID: 45e96b8224f3
Revises: 
Create Date: 2026-03-26 01:30:06.661593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45e96b8224f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_index(op.f('idx_postings_doc_id'), table_name='postings')
    op.drop_index(op.f('idx_postings_token_id'), table_name='postings')
    op.drop_table('postings')
    op.drop_index(op.f('idx_tokens_token'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_table('documents')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('tokens_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_tokens_token'), 'tokens', ['token'], unique=False)
    op.create_table('postings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doc_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('positions', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], name=op.f('postings_doc_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], name=op.f('postings_token_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('postings_pkey'))
    )
    op.create_index(op.f('idx_postings_token_id'), 'postings', ['token_id'], unique=False)
    op.create_index(op.f('idx_postings_doc_id'), 'postings', ['doc_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    # ### end Alembic commands ###
